chaiheadq/chaiheadq/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth.urls import views as auth_views


urlpatterns = [
    path("", include('tweet.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

chaiheadq/tweet/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.tweet_list, name='tweet_list'),
    path('create/', views.tweet_create, name='tweet_create'),
    path('<int:tweet_id>/edit/', views.tweet_edit, name='tweet_edit'),
    path('<int:tweet_id>/delete/', views.tweet_delete, name='tweet_delete'),
    path('register/', views.register, name='register'),
    path('search/', views.search, name='search'),
]

chaiheadq/tweet/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Tweet(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE)
    text = models.TextField(max_length = 240)
    photo = models.ImageField(upload_to = 'photos/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user.username} - {self.text[:10]}'

chaiheadq/tweet/forms.py
from django import forms
from .models import Tweet
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class TweetForm(forms.ModelForm):
    class Meta:
        model = Tweet
        fields = ['text', 'photo']
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter your tweet here'}),
            'photo': forms.FileInput(attrs={'class': 'form-control-file'}),
        }
    
class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

chaiheadq/chaiheadq/views.py
from django.http import HttpResponse

def home(request):
    return HttpResponse("Hello, World. Home Page")

chaiheadq/tweet/views.py
from django.shortcuts import render
from .models import Tweet
from .forms import TweetForm, UserRegistrationForm
from django.shortcuts import get_object_or_404,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.db.models import Q

# Create your views here.

def index(request):
    return render(request, 'index.html')

def tweet_list(request):
    tweets = Tweet.objects.all().order_by('-created_at')
    return render(request, 'tweet_list.html', {'tweets':tweets})  

@login_required
def tweet_create(request):
    form = None
    if request.method == "POST":
        form = TweetForm(request.POST, request.FILES)
        if form.is_valid():
            tweet = form.save(commit = False)
            tweet.user = request.user
            tweet.save()
            return redirect('tweet_list')
    else:
        form = TweetForm()
    return render(request, 'tweet_form.html', {'form':form})

@login_required
def tweet_edit(request, tweet_id):
    tweet = get_object_or_404(Tweet, pk=tweet_id, user = request.user)
    if request.method == "POST":
        form = TweetForm(request.POST, request.FILES, instance=tweet)
        if form.is_valid():
            tweet = form.save(commit = False)
            tweet.user = request.user
            tweet.save()
            return redirect('tweet_list')
    else:
        form = TweetForm(instance = tweet)
    return render(request, 'tweet_form.html', {'form':form})

@login_required
def tweet_delete(request, tweet_id):
    tweet = get_object_or_404(Tweet, pk=tweet_id, user=request.user)
    if request.method == 'POST':
        tweet.delete()
        return redirect('tweet_list')
    return render(request, 'tweet_confirm_delete.html', {'tweet':tweet})

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit = False)
            user.set_password(form.cleaned_data['password1'])
            user.save()
            login(request,user)
            return redirect('tweet_list')
    else:
        form = UserRegistrationForm()
    return render(request, 'registration/register.html',{'form':form})

def search(request):
    query = request.GET["query"]
    tweets = Tweet.objects.filter( Q(text__icontains=query) | Q(user__username__icontains=query))
    return render(request, 'search.html', {"tweets":tweets}) 

chaiheadq/templates/layout.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>
        {% block title %}
        Title
        {% endblock  %}
    </title>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand fs-3 fw-bold" href="{% url 'tweet_list' %}">Tweets</a>
    
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
    
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item d-flex align-items-center">
                        <!-- Username -->
                        <span class="navbar-text text-light fs-5 fw-bold me-3">{{ user.username|capfirst }}</span>
                        <!-- Logout Button -->
                        <form method="post" action="{% url 'logout' %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Logout</button>
                        </form>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="btn btn-primary me-2" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-secondary" href="{% url 'register' %}">Register</a>
                    </li>
                    {% endif %}
    
                    <!-- Search Form -->
                    <li class="nav-item ms-3" >
                        <form class="d-flex" action="{% url 'search' %}" method="get">
                            <input class="form-control me-2" type="search" placeholder="Search tweets" aria-label="Search" name="query" id="query">
                            <button class="btn btn-outline-light" type="submit">Search</button>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </nav>



    {% load widget_tweaks %}
    <div class="container">
    {% block content %}
    
    {% endblock  %}
    </div>
</body>
</html>

chaiheadq/tweet/templates/index.html
{% extends "layout.html" %}

{% block title %}
tweet
{% endblock  %}

{% block content %}
<h1 class='text-center'>Welcome to tweet page</h1>
{% endblock  %}

chaiheadq/tweet/templates/search.html
{% extends "layout.html" %}

{% block title %}
tweet
{% endblock  %}

{% block content %}

<a class="btn btn-primary mb-4" href={% url  'tweet_list' %}>Back</a>
<div class="container row gap-3">

<h2>Search Results:</h2>

{% for tweet in tweets%}
<div class="card" style="width: 18rem;padding: 0;">
  <!-- Set a fixed height for the image and use object-fit to maintain aspect ratio -->
  <img src="{{ tweet.photo.url }}" class="card-img-top" alt="..." style="height: 200px; object-fit: cover;">
  <div class="card-body">
      <!-- Capitalize the first letter of the username -->
      <h5 class="card-title">{{ tweet.user.username|capfirst }}</h5>
      <p class="card-text">{{ tweet.text }}</p>
      {% if  tweet.user == user%}
      <a href="{% url 'tweet_edit' tweet.id %}" class="btn btn-primary m-1">Edit</a>
      <a href="{% url 'tweet_delete' tweet.id %}" class="btn btn-danger m-1">Delete</a>
      {% endif %}
  </div>
</div>
{% endfor %}

</div>

{% endblock  %}

chaiheadq/tweet/templates/tweet_confirm_delete.html
{% extends "layout.html" %}

{% block title %}
tweet
{% endblock  %}

{% block content %}
<h1 class='text-center'>Delete Tweet!!</h1>
<form method="post">
    {% csrf_token %}
<div class="d-flex justify-content-center align-items-center" style="min-height: 70vh;">
<div class="card" style="width: 18rem;padding: 0;">
    <!-- Set a fixed height for the image and use object-fit to maintain aspect ratio -->
    <img src="{{ tweet.photo.url }}" class="card-img-top" alt="..." style="height: 200px; object-fit: cover;">
    <div class="card-body">
        <!-- Capitalize the first letter of the username -->
        <h5 class="card-title">{{ tweet.user.username|capfirst }}</h5>
        <p class="card-text">{{ tweet.text }}</p><div class="row">
            <div class="col-6">
                <button type="submit" class="btn btn-danger w-100">Delete</button>
            </div>
            <div class="col-6">
                <a href="{% url 'tweet_list' %}" class="btn btn-secondary btn-block w-100">Cancel</a>
            </div>
        </div>
    </div>
  </div>
</div>
</form>
{% endblock  %}

chaiheadq/tweet/templates/tweet_form.html
{% extends "layout.html" %}

{% block title %}
tweet
{% endblock  %}

{% block content %}

<h1 class='text-center'>
    {% if form.instance.pk %}
    Edit Tweet
    {% else %}
    Create Tweet
    {% endif %}
</h1>

<form method="post" enctype="multipart/form-data" class="form">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h3 class="card-title text-center mb-4">Upload Form</h3>

                        <!-- CSRF Token -->
                        {% csrf_token %}

                        <!-- Render the text input field with margin-bottom -->
                        <div class="form-group mb-4">
                            <label for="id_text" class="mb-1">Enter Tweet:</label>
                            {{ form.text }}
                        </div>

                        <!-- Render the file input field -->
                        <div class="form-group mb-4">
                            <label for="id_photo">Choose Photo</label>
                            {{ form.photo }}
                        </div>

                        <!-- Button Group: Submit and Cancel buttons side by side -->
                        <div class="row">
                            <div class="col-6">
                                <button type="submit" class="btn btn-primary w-100">Submit</button>
                            </div>
                            <div class="col-6">
                                <a href="{% url 'tweet_list' %}" class="btn btn-secondary btn-block w-100">Cancel</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>




{% endblock  %}

chaiheadq/tweet/templates/tweet_list.html
{% extends "layout.html" %}

{% block title %}
tweet
{% endblock  %}

{% block content %}
<h1 class='text-center'>Welcome to Tweet page!</h1>

<a class="btn btn-primary mb-4" href={% url  'tweet_create' %}>Create a Tweet</a>
<div class="container row gap-3">

{% for tweet in tweets%}
<div class="card" style="width: 18rem;padding: 0;">
  <!-- Set a fixed height for the image and use object-fit to maintain aspect ratio -->
  <img src="{{ tweet.photo.url }}" class="card-img-top" alt="..." style="height: 200px; object-fit: cover;">
  <div class="card-body">
      <!-- Capitalize the first letter of the username -->
      <h5 class="card-title">{{ tweet.user.username|capfirst }}</h5>
      <p class="card-text">{{ tweet.text }}</p>
      {% if  tweet.user == user%}
      <a href="{% url 'tweet_edit' tweet.id %}" class="btn btn-primary m-1">Edit</a>
      <a href="{% url 'tweet_delete' tweet.id %}" class="btn btn-danger m-1">Delete</a>
      {% endif %}
  </div>
</div>
{% endfor %}

</div>

{% endblock  %}